name: server

services:
  application:
    build:
      context: ./../
      dockerfile: ./docker/dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - server-logs:/var/logs/nginx/
      - server-certificates:/etc/letsencrypt/
    networks:
      - server-network

networks:
  server-network:
    name: server-network

volumes:
  server-logs:
    name: server-logs
  server-certificates:
    name: server-certificates
