name: server

services:
  application:
    build:
      context: ./../
      dockerfile: dockerfile
      args:
        - DEPLOY_PRIMARY_DOMAIN=${DEPLOY_PRIMARY_DOMAIN}
        - DEPLOY_DOMAINS=${DEPLOY_DOMAINS}
        - DEPLOY_DOMAINS_MAPPER=${DEPLOY_DOMAINS_MAPPER}
        - DEPLOY_EMAIL=${DEPLOY_EMAIL}
    ports:
      - 80:80
      - 443:443
    volumes:
      - server-logs:/var/logs/nginx/
    networks:
      - server-network

networks:
  server-network:
    name: server-network

volumes:
  server-logs:
    name: server-logs
