worker_processes 1;

events {
  worker_connections 1024;
}

http {
  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;

  server {
    listen 80;
    server_name egorchumichev.dev www.egorchumichev.dev;

    location / {
      return 301 https://$host$request_uri;
    }
  }

  map $host $container {
    default docker-container-1;

    egorchumichev.dev blog-frontend-application-1;
    www.egorchumichev.dev blog-frontend-application-1;
  }

  server {
    listen 443 ssl;
    server_name egorchumichev.dev www.egorchumichev.dev;

    ssl_certificate /etc/letsencrypt/live/egorchumichev.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/egorchumichev.dev/privkey.pem;

    location / {
      proxy_pass http://$container;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
